title: Zaid Kokaja
author: zkokaja
email: 
description: >
  Developer, Student, Consultant

# social links
rss: rss
#twitter_username: jekyllrb
github_username:  zkokaja
flickr_username: zkokaja
linkedin_username: zkokaja

# dribbble_username: jekyll
# facebook_username: jekyll
# instagram_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

permalink: /:year/:month/:day/:title/

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
